export component ProjectorWindow inherits Window {
    no-frame: true;
    always-on-top: true;
    title: "";
    background: root.bg_color;

    in property <string> texto_proyeccion: "";
    in property <string> referencia: "";
    in property <float> tamano_letra: 85;
    in property <color> bg_color: black;
    in property <color> text_color: white;
    
    in property <image> fondo_imagen;
    in property <bool> mostrar_imagen: false;

    // --- NUEVAS PROPIEDADES DE VIDEO ---
    in property <image> fondo_video_frame;
    in property <bool> es_video: false;
    in property <float> fondo_opacity: 0.4;
    

    // Capa 1: Imagen estática
    if (root.mostrar_imagen && !root.es_video) : Image {
        source: root.fondo_imagen;
        width: 100%; height: 100%;
        image-fit: cover;
    }

    // Capa 1.5: Video Nativo (Fotogramas inyectados desde Rust)
    if (root.es_video) : Image {
        source: root.fondo_video_frame;
        width: 100%; height: 100%;
        image-fit: cover;
    }

    // Capa 2: Oscurecer el fondo para que las letras resalten
    // [¡BUG CORREGIDO AQUI!] Ahora lee 'root.fondo_opacity' en lugar de 0.4
    Rectangle {
        width: 100%; height: 100%;
        background: rgba(0, 0, 0, root.fondo_opacity);
    }
    VerticalLayout {
        padding: 50px;
        padding-bottom: root.referencia != "" ? 16px : 50px;
        spacing: 0px;

        Rectangle {
            vertical-stretch: 1;
            background: transparent;
            Text {
                text: root.texto_proyeccion;
                color: root.text_color;
                font-size: root.tamano_letra * 1px;
                font-weight: 900;
                wrap: word-wrap;
                horizontal-alignment: center;
                vertical-alignment: center;
                width: parent.width;
                height: parent.height;
            }
        }

        if (root.referencia != "") : Rectangle {
            height: 70px;
            background: transparent;
            Text {
                text: root.referencia;
                color: root.text_color;
                font-size: 36px;
                font-weight: 800;
                font-italic: true;
                horizontal-alignment: right;
                vertical-alignment: center;
                width: parent.width;
                height: parent.height;
            }
        }
    }
}